# Generated by Django 4.1 on 2022-09-12 03:09

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from=models.CharField(max_length=300), unique=True),
        ),
    ]
